<?php
return [
    'chapter06-what-the-summer-took' => null,
    'chapter06-black-earth' => 'chapter06-give-us-this-day',
    'chapter07-black-earth' => 'chapter06-give-us-this-day',
    'chapter07-the-contract' => 'chapter08-the-contract',
    'chapter08-the-crossing' => 'chapter09-the-crossing',
    'chapter09-wide-open-spaces' => 'chapter10-wide-open-spaces',
    'chapter10-the-quiet-son' => 'chapter11-the-quiet-son',
    'chapter11-in-this-place-we-do-not-want-to-die' => 'chapter12-in-this-place-we-do-not-want-to-die',
    'chapter12-the-hardware-store' => 'chapter13-the-hardware-store',
    'chapter13-the-golden-wedding' => 'chapter14-the-golden-wedding',
    'chapter14-the-beloved-journeys' => 'chapter15-the-beloved-journeys',
    'chapter15-the-corporal' => 'chapter16-the-corporal',
    'chapter16-the-childrens-hour' => 'chapter17-the-childrens-hour',
    'chapter17-tante-frieda' => 'chapter18-tante-frieda',
    'chapter18-apparel-art' => 'chapter19-apparel-art',
    'chapter19-south' => 'chapter20-south',
    'chapter20-pig-feet' => 'chapter21-pig-feet',
];
